services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      # Строку с db_data мы убрали, так как папка проекта уже подключена целиком
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1