# Generated by Django 4.2.7 on 2026-05-15 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('order_created', 'Заказ создан'), ('order_status_changed', 'Статус заказа изменён'), ('item_added_to_cart', 'Товар добавлен в корзину'), ('payment_made', 'Оплата произведена'), ('user_logged_in', 'Пользователь вошёл в систему')], max_length=50, verbose_name='Действие')),
                ('object_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действий',
                'verbose_name_plural': 'Логи действий',
                'ordering': ['-timestamp'],
            },
        ),
    ]
